# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: SUSE IDP Portal
subTitle: The Community Accounts Migration
email: not-yet-published_noreply@example.com
author: J. Daniel Schmidt
description: The Community Accounts (aka. Bugzilla Accounts) will migration to the SUSE datacenter in Nuremberg
copyright: 'Copyright &copy; 2020 SUSE. All Rights Reserved.'
github_organization: SUSE
github_repository: idp-portal
gems:
  - jekyll-redirect-from
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

#collections:
#- gsoc_current
